// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn5bY8n4TKDD9xyBS16sK7-uFaFqPA-9k',
    appId: '1:634760010285:web:55a7ffe9dfc33097cc76a4',
    messagingSenderId: '634760010285',
    projectId: 'flutter-app-expenses01',
    authDomain: 'flutter-app-expenses01.firebaseapp.com',
    storageBucket: 'flutter-app-expenses01.appspot.com',
    measurementId: 'G-WM4QGR6271',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_fH-Q1z0nwyFBYkWIZtQb1xt_genQSI',
    appId: '1:634760010285:android:f96b72de3d28165acc76a4',
    messagingSenderId: '634760010285',
    projectId: 'flutter-app-expenses01',
    storageBucket: 'flutter-app-expenses01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRU4DZ--okERcRejTCIRfBwhr2tMzZNs',
    appId: '1:634760010285:ios:f8a716616c9dd56ccc76a4',
    messagingSenderId: '634760010285',
    projectId: 'flutter-app-expenses01',
    storageBucket: 'flutter-app-expenses01.appspot.com',
    iosClientId: '634760010285-lmuklnpt4skbdvjif4s5bjhll55cmihr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRU4DZ--okERcRejTCIRfBwhr2tMzZNs',
    appId: '1:634760010285:ios:66bf61fc2b9f3cc8cc76a4',
    messagingSenderId: '634760010285',
    projectId: 'flutter-app-expenses01',
    storageBucket: 'flutter-app-expenses01.appspot.com',
    iosClientId: '634760010285-6h1o7mqh0aqufmbddeqjtum43i177mkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerApp.RunnerTests',
  );
}
